CREATE SEQUENCE JOB_TEST_SEQ;
DROP SEQUENCE JOB_TEST_SEQ;

CREATE TABLE JOB_TEST01(NO NUMBER, NAME VARCHAR2(10));
DROP TABLE JOB_TEST01;

CREATE OR REPLACE PROCEDURE INSERT_JOB_TEST01
IS
DECLARE
    
BEGIN
	INSERT INTO JOB_TEST01 VALUES(JOB_TEST_SEQ.NEXTVAL,
		DBMS_RANDOM.STRING('A', 3));
END ;

DROP PROCEDURE INSERT_JOB_TEST02;


DECLARE
	JNO NUMBER;
BEGIN
	DBMS_JOB.SUBMIT(JNO, 
			'INSERT_JOB_TEST02;',
			sysdate,
			'SYSDATE+1/1440',
			FALSE);
END;

SELECT * FROM USER_JOBS
SELECT * FROM EA_PLIST
SELECT * FROM EA_SLIST
select * from EA_BOARD

 		update ea_board set eb_ladate = to_date('2018-08-02 12:34:00','YYYY-MM-DD HH24:MI:SS') where eb_itemnum = 'CP18080232'
 		update ea_board set eb_audate = to_date('2018-08-02 11:40:00','YYYY-MM-DD HH24:MI:SS') where eb_itemnum = 'CP18080232'
SELECT * FROM INSERT_JOB_TEST02
delete ea_plist2


COMMIT

DECLARE
BEGIN
	DBMS_JOB.REMOVE(14);
	COMMIT;
END;

-----------------------1분마다 반복-----------------------
DECLARE
	PRO_ITEMNO EA_BOARD.EB_ITEMNUM%TYPE;
BEGIN
			EXECUTE IMMEDIATE 'SELECT EB_ITEMNUM FROM EA_BOARD WHERE EB_ITEMNAME = ''슬램덩크'' '
			INTO PRO_ITEMNO;
			
			DBMS_OUTPUT.PUT_LINE( 'PRO_ITEMNO : '   || PRO_ITEMNO );
END;

SELECT * FROM EA_GHOUSE
SELECT * FROM EA_BOARD


SELECT * FROM (SELECT EA_BOARD.EB_ITEMNUM, EA_BOARD.EB_STATE,EA_GHOUSE.GH_BUYER,EA_BOARD.EM_ID,
								EA_BOARD.EB_BOARDNUM, EA_BOARD.EB_ITEMNAME, EA_BOARD.EB_FILE, EA_BOARD.EB_LAPRICE 
								FROM EA_BOARD 
								INNER JOIN EA_GHOUSE
								ON EA_BOARD.EB_ITEMNUM = EA_GHOUSE.EB_ITEMNUM
	 							WHERE eb_ladate + 1/(24*60) between sysdate and sysdate + 1/(24*60) 
	 							ORDER BY EB_LAPRICE DESC)WHERE ROWNUM = 1


SELECT * FROM JOIN_MEMBER


--------------------- 경매 종료된 게시물 가져오기 (그중에서 가장 최신으로 종료된 순서대로)

SET TIMING ON

CREATE OR REPLACE PROCEDURE INSERT_JOB_TEST02
IS
	PRO_ITEMNUM EA_BOARD.EB_ITEMNUM%TYPE;
	PRO_STATE EA_BOARD.EB_STATE%TYPE;
	PRO_USER EA_GHOUSE.GH_BUYER%TYPE;
	PRO_SELLER EA_BOARD.EM_ID%TYPE;
	PRO_BOARDNUM EA_BOARD.EB_BOARDNUM%TYPE;
	PRO_ITEMNAME EA_BOARD.EB_ITEMNAME%TYPE;
	PRO_FILE EA_BOARD.EB_FILE%TYPE;
	PRO_PRICE EA_BOARD.EB_LAPRICE%TYPE;
BEGIN
			EXECUTE IMMEDIATE 'SELECT * FROM (SELECT EA_BOARD.EB_ITEMNUM, EA_BOARD.EB_STATE,EA_GHOUSE.GH_BUYER,EA_BOARD.EM_ID,
								EA_BOARD.EB_BOARDNUM, EA_BOARD.EB_ITEMNAME, EA_BOARD.EB_FILE, EA_BOARD.EB_LAPRICE 
								FROM EA_BOARD 
								INNER JOIN EA_GHOUSE
								ON EA_BOARD.EB_ITEMNUM = EA_GHOUSE.EB_ITEMNUM
	 							WHERE eb_ladate + 1/(24*60) between sysdate and sysdate + 1/(24*60) 
	 							ORDER BY EB_LAPRICE DESC)WHERE ROWNUM = 1'
			
			INTO PRO_ITEMNUM,PRO_STATE,PRO_USER,PRO_SELLER,PRO_BOARDNUM,PRO_ITEMNAME,PRO_FILE,PRO_PRICE;
			
											DBMS_OUTPUT.PUT_LINE( 'PRO_ITEMNUM : '   || PRO_ITEMNUM );
											DBMS_OUTPUT.PUT_LINE( 'PRO_STATE : '   || PRO_STATE );
											DBMS_OUTPUT.PUT_LINE( 'PRO_USER : '   || PRO_USER );
											DBMS_OUTPUT.PUT_LINE( 'PRO_SELLER : '   || PRO_SELLER );
											DBMS_OUTPUT.PUT_LINE( 'PRO_BOARDNUM : '   || PRO_BOARDNUM );
											DBMS_OUTPUT.PUT_LINE( 'PRO_ITEMNAME : '   || PRO_ITEMNAME );
											DBMS_OUTPUT.PUT_LINE( 'PRO_FILE : '   || PRO_FILE );
											DBMS_OUTPUT.PUT_LINE( 'PRO_PRICE : '   || PRO_PRICE );
											
											INSERT INTO EA_PLIST VALUES (JOB_TEST_SEQ.NEXTVAL,PRO_STATE,PRO_USER,PRO_SELLER,PRO_BOARDNUM,PRO_ITEMNUM,PRO_ITEMNAME,PRO_FILE,PRO_PRICE,SYSDATE,'구매완료');
											INSERT INTO EA_SLIST VALUES (JOB_TEST_SEQ.NEXTVAL,PRO_STATE,PRO_SELLER,PRO_USER,PRO_BOARDNUM,PRO_ITEMNUM,PRO_ITEMNAME,PRO_FILE,PRO_PRICE,SYSDATE);
											UPDATE EA_BOARD SET EB_LAPRICE = PRO_PRICE, EB_SALEDATE = SYSDATE WHERE EB_ITEMNUM = PRO_ITEMNUM;
											
								COMMIT;
								END;
								
 		update ea_board set eb_audate = to_date('2018-08-01 17:12:00','YYYY-MM-DD HH24:MI:SS') where eb_itemnum = 'CP18080126'
 		update ea_board set eb_ladate = to_date('2018-08-01 18:16:30','YYYY-MM-DD HH24:MI:SS') where eb_itemnum = 'CP18080126'
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

								
								
											INSERT INTO EA_PLIST2 (EP_NUM,EP_KIND,EP_USER,EP_SELLER,EB_BOARDNUM,EB_ITEMNUM,EB_ITEMNAME,EB_FILE,EP_PRICE,EP_DATE) 
											VALUES (JOB_TEST_SEQ.NEXTVAL,PRO_STATE,PRO_USER,PRO_SELLER,PRO_BOARDNUM,PRO_ITEMNUM,PRO_ITEMNAME,PRO_FILE,PRO_PRICE,SYSTE);
								
SELECT * FROM EA_BOARD WHERE EB_LADATE > sysdate and EB_ladate < sysdate + 1/(24*60) 
SELECT * FROM EA_PLIST2
commit;

CREATE TABLE EA_TEST (ITEMNO VARCHAR2(50))
INSERT INTO EA_PLIST2(EP_NUM,EP_KIND,EP_USER,EP_SELLER,EB_BOARDNUM,EB_ITEMNUM,EB_ITEMNAME,EB_FILE,EB_PRICE,EP_DATE) VALUES(JOB_TEST_SEQ.NEXTVAL,PRO_STATE,PRO_USER,PRO_SELLER,PRO_BOARDNUM,PRO_ITEMNUM,PRO_ITEMNAME,PRO_FILE,PRO_PRICE,SYSDATE);
			
SELECT * FROM EA_TEST
INSERT INTO EA_TEST VALUES('안녕');
---------------------- 경매 종료된 게시물 가져오기 (최신꺼 , 그리고 최고입찰자 조인)

		SELECT * FROM (SELECT EA_BOARD.EB_ITEMNUM, EA_BOARD.EB_STATE,EA_GHOUSE.GH_BUYER,EA_BOARD.EM_ID,EA_BOARD.EB_ladate,
								EA_BOARD.EB_BOARDNUM, EA_BOARD.EB_ITEMNAME, EA_BOARD.EB_FILE, EA_BOARD.EB_LAPRICE 
								FROM EA_BOARD 
								INNER JOIN EA_GHOUSE
								ON EA_BOARD.EB_ITEMNUM = EA_GHOUSE.EB_ITEMNUM
	 							WHERE eb_ladate + 1/(24*60) between sysdate and sysdate + 1/(24*60) 
	 							ORDER BY EB_LAPRICE DESC)WHERE ROWNUM = 1
	 							
	 							
SELECT * 
FROM EA_BOARD 
	INNER JOIN EA_GHOUSE
	ON EA_BOARD.EB_ITEMNUM = EA_GHOUSE.EB_ITEMNUM
	 WHERE EB_LADATE > sysdate and EB_ladate < sysdate + 1/(24*60)
	


select sysdate from dual
 		



select to_data(eb_ladate) from ea_board 


    BEGIN
      EXECUTE IMMEDIATE 'SELECT EB_ITEMNUM FROM EA_BOARD WHERE EB_ITEMNAME = ''슬램덩크'' ';
    END;

SELECT * FROM EA_BOARD WHERE EB_ITEMNAME = '슬램덩크'


SET TIMING ON


CREATE OR REPLACE PROCEDURE INSERT_JOB_TEST02
IS
	PRO_ITEMNUM EA_BOARD.EB_ITEMNUM%TYPE;
	PRO_STATE EA_BOARD.EB_STATE%TYPE;
	PRO_USER EA_GHOUSE.GH_BUYER%TYPE;
	PRO_SELLER EA_BOARD.EM_ID%TYPE;
	PRO_BOARDNUM EA_BOARD.EB_BOARDNUM%TYPE;
	PRO_ITEMNAME EA_BOARD.EB_ITEMNAME%TYPE;
	PRO_FILE EA_BOARD.EB_FILE%TYPE;
	PRO_PRICE EA_BOARD.EB_LAPRICE%TYPE;
BEGIN
			EXECUTE IMMEDIATE 'SELECT DISTINCT EA_BOARD.EB_ITEMNUM, EA_BOARD.EB_STATE,EA_GHOUSE.GH_BUYER,EA_BOARD.EM_ID,
								EA_BOARD.EB_BOARDNUM, EA_BOARD.EB_ITEMNAME, EA_BOARD.EB_FILE, EA_BOARD.EB_LAPRICE 
								FROM EA_BOARD 
								INNER JOIN EA_GHOUSE
								ON EA_BOARD.EB_ITEMNUM = EA_GHOUSE.EB_ITEMNUM
	 							WHERE eb_ladate + 1/(24*60) between sysdate and sysdate + 1/(24*60)'
			
			INTO PRO_ITEMNUM,PRO_STATE,PRO_USER,PRO_SELLER,PRO_BOARDNUM,PRO_ITEMNAME,PRO_FILE,PRO_PRICE;
			
											DBMS_OUTPUT.PUT_LINE( 'PRO_ITEMNUM : '   || PRO_ITEMNUM );
											DBMS_OUTPUT.PUT_LINE( 'PRO_STATE : '   || PRO_STATE );
											DBMS_OUTPUT.PUT_LINE( 'PRO_USER : '   || PRO_USER );
											DBMS_OUTPUT.PUT_LINE( 'PRO_SELLER : '   || PRO_SELLER );
											DBMS_OUTPUT.PUT_LINE( 'PRO_BOARDNUM : '   || PRO_BOARDNUM );
											DBMS_OUTPUT.PUT_LINE( 'PRO_ITEMNAME : '   || PRO_ITEMNAME );
											DBMS_OUTPUT.PUT_LINE( 'PRO_FILE : '   || PRO_FILE );
											DBMS_OUTPUT.PUT_LINE( 'PRO_PRICE : '   || PRO_PRICE );
											
											INSERT INTO EA_PLIST2 (EP_NUM,EP_KIND,EP_USER,EP_SELLER,EB_BOARDNUM,EB_ITEMNUM,EB_ITEMNAME,EB_FILE,EP_PRICE,EP_DATE) VALUES (JOB_TEST_SEQ.NEXTVAL,PRO_STATE,PRO_USER,PRO_SELLER,PRO_BOARDNUM,PRO_ITEMNUM,PRO_ITEMNAME,PRO_FILE,PRO_PRICE,SYSDATE);
										
								END;

select * from user_procedures


